### ISSUE TITLE
chmod of gradlew cause Gitlab CI build to fail

### ISSUE THREAD

**Issue by andyflowersnaimuri** [paketo-buildpacks/gradle#153]
## What happened?

* What were you attempting to do?
Run a Gitlab CI pipeline using DinD workaround from https://blog.codecentric.de/en/2021/10/gitlab-ci-paketo-buildpacks/ as no ability to do DinD at the moment. The image runs as the cnb user which has no rights in the CI environment (which may be a different issue which is noted elsewhere).

* What did you expect to happen?
The build to complete with no issues.
It would be good if before the unconditional chmod of gradlew the builder tests if it is needed, and if not just skips the step such that we can run in environments where the docker image we are running within has no rights to modify parts of the underlying filesystem.

* What was the actual behavior? Please provide log output, if possible.
Failed to chmod gradlew.

```
Paketo Gradle Buildpack 6.4.2
  unable to chmod /.../.../.../.../.../examples/java/gradlew
  chmod .../.../.../.../.../examples/java/gradlew: operation not permitted
```

**Comment by dmikusa-pivotal** [comment]
Sure we can do that. Alternatively, we could perhaps just log the error as a warning and try to proceed anyway. That way if the permissions are OK, we'll just keep going. Either seems reasonable and we can look at making the change.

**Comment by dmikusa-pivotal** [comment]
FYI, if anyone is interested this would be a good issue for a new contributor.

**Comment by cz4rny** [comment]
@dmikusa-pivotal As you've mentioned in the `maven` variant fo this package, I'm presenting a PR to fix `gradlew` checking first. Once this gets approved, I'll copy the one to [the maven bug](https://github.com/paketo-buildpacks/maven/issues/150).

**Comment by cz4rny** [comment]
@dmikusa-pivotal Thanks for merging my PR and closing this issue.

Now how could I start using the fruits of my labour? I.e. how can I trigger release or use a snapshot build within my pipelines?

**Comment by cz4rny** [comment]
Well I'm not using `pack`, I'm using the `paketobuildpacks/builder:base` image and calling

````yaml
/cnb/lifecycle/creator
      -platform "$PLATFORM_DIR"
      -app=.
      $CI_REGISTRY_IMAGE:latest
````

This is in order to have userspace build on GitLab runners as described in the great article by Tekton crew:
https://blog.codecentric.de/en/2021/10/gitlab-ci-paketo-buildpacks/

I would hope then, that after Friday the `latest` image of `paketobuildpacks/builder:base` will get the newer gradle or maven buildpack and thus save humankind from a cataclysmic event of not being able to call `gradlew` or `mvnw`.

**Comment by dmikusa-pivotal** [comment]
>I would hope then, that after Friday the latest image of paketobuildpacks/builder:base will get the newer gradle or maven buildpack and thus save humankind from a cataclysmic event of not being able to call gradlew or mvnw.

Sorry, my fault. That's the whole reason behind this issue 🤦 

Yes, your best bet is to wait till Friday. We usually cut buildpack releases in the morning US EST and the builder updates 30 mins or so after that, so if you don't see the update by noon, give me a ping. I can check and make sure the builder pipeline didn't get jammed up, that happens occasionally.

Thanks

**Comment by dmikusa-pivotal** [comment]
Releases of the Paketo Java composite buildpacks with this fix have been cut. The builder updates run automatically and are typically available within 30 mins, so they should be out by 9:45 or 10:00am EST.

**Comment by cz4rny** [comment]
Hey @dmikusa-pivotal , works flawlessly today! Thank you!
