### ISSUE TITLE
Buildpack tries to access git hook

### ISSUE THREAD

**Issue by Haegi** [paketo-buildpacks/gradle#70]
## What happened?

* What were you attempting to do?

  I tried to build the [spring-music](https://github.com/scottfrederick/spring-music) cloudfoundry sample app with pack and a paketo builder.

* What did you expect to happen?

  I expected that the build will be successful and an OCI will be produced.

* What was the actual behavior? Please provide log output, if possible.

  The build fails in the Gradle Paketo Buildpacks step because it tries to load some git hooks (e.g. `open /workspace/.git/hooks/pre-commit: no such file or directory`). This is a git hook specified by my team. But why does the buildpack want to access the hook as it is normally just used by git and I can't find anything git related in this buildpack?

  ```bash
  > git clone git@github.com:scottfrederick/spring-music.git
  [...]
  > cd spring-music
  > pack build spring-music --builder paketobuildpacks/builder:base                                              
  base: Pulling from paketobuildpacks/builder
  Digest: sha256:583b30158deddb27e5e8f78489e12fb5e77340f2ecd8e82ba300e28e58475955
  Status: Image is up to date for paketobuildpacks/builder:base
  base-cnb: Pulling from paketobuildpacks/run
  Digest: sha256:956341a43edf4029b29114502f7deb185527aed63e2a5ab94d86cd33abb34e56
  Status: Image is up to date for paketobuildpacks/run:base-cnb
  ===> DETECTING
  7 of 18 buildpacks participating
  paketo-buildpacks/ca-certificates   2.2.0
  paketo-buildpacks/bellsoft-liberica 8.0.0
  paketo-buildpacks/gradle            5.2.0
  paketo-buildpacks/executable-jar    5.0.0
  paketo-buildpacks/apache-tomcat     5.3.0
  paketo-buildpacks/dist-zip          4.0.0
  paketo-buildpacks/spring-boot       4.2.0
  ===> ANALYZING
  Skipping buildpack layer analysis
  ===> BUILDING
  
  Paketo CA Certificates Buildpack 2.2.0
    https://github.com/paketo-buildpacks/ca-certificates
    Launch Helper: Contributing to layer
      Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
  
  Paketo BellSoft Liberica Buildpack 8.0.0
    https://github.com/paketo-buildpacks/bellsoft-liberica
    Build Configuration:
      $BP_JVM_VERSION              11              the Java version
    Launch Configuration:
      $BPL_JVM_HEAD_ROOM           0               the headroom in memory calculation
      $BPL_JVM_LOADED_CLASS_COUNT  35% of classes  the number of loaded classes in memory calculation
      $BPL_JVM_THREAD_COUNT        250             the number of threads in memory calculation
      $JAVA_TOOL_OPTIONS                           the JVM launch flags
    BellSoft Liberica JDK 11.0.11: Contributing to layer
      Downloading from https://github.com/bell-sw/Liberica/releases/download/11.0.11+9/bellsoft-jdk11.0.11+9-linux-amd64.tar.gz
       Verifying checksum
      Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jdk
      Adding 129 container CA certificates to JVM truststore
      Writing env.build/JAVA_HOME.override
      Writing env.build/JDK_HOME.override
    BellSoft Liberica JRE 11.0.11: Contributing to layer
      Downloading from https://github.com/bell-sw/Liberica/releases/download/11.0.11+9/bellsoft-jre11.0.11+9-linux-amd64.tar.gz
      Verifying checksum
      Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
      Adding 129 container CA certificates to JVM truststore
      Writing env.launch/BPI_APPLICATION_PATH.default
      Writing env.launch/BPI_JVM_CACERTS.default
      Writing env.launch/BPI_JVM_CLASS_COUNT.default
      Writing env.launch/BPI_JVM_SECURITY_PROVIDERS.default
      Writing env.launch/JAVA_HOME.default
      Writing env.launch/MALLOC_ARENA_MAX.default
    Launch Helper: Contributing to layer
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/active-processor-count
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/java-opts
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/link-local-dns
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/memory-calculator
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/openssl-certificate-loader
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-configurer
      Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-classpath-9
    JVMKill Agent 1.16.0: Contributing to layer
      Downloading from https://github.com/cloudfoundry/jvmkill/releases/download/v1.16.0.RELEASE/jvmkill-1.16.0-RELEASE.so
      Verifying checksum
      Copying to /layers/paketo-buildpacks_bellsoft-liberica/jvmkill
      Writing env.launch/JAVA_TOOL_OPTIONS.append
      Writing env.launch/JAVA_TOOL_OPTIONS.delim
    Java Security Properties: Contributing to layer
      Writing env.launch/JAVA_SECURITY_PROPERTIES.default
      Writing env.launch/JAVA_TOOL_OPTIONS.append
      Writing env.launch/JAVA_TOOL_OPTIONS.delim
  
  Paketo Gradle Buildpack 5.2.0
    https://github.com/paketo-buildpacks/gradle
    Build Configuration:
      $BP_GRADLE_BUILD_ARGUMENTS  --no-daemon assemble  the arguments to pass to Gradle
      $BP_GRADLE_BUILT_ARTIFACT   build/libs/*.[jw]ar   the built application artifact explicitly.  Supersedes $BP_GRADLE_BUILT_MODULE
      $BP_GRADLE_BUILT_MODULE                           the module to find application artifact in
  
  Paketo Gradle Buildpack 5.2.0
    unable to create application layer
    failed to generate expected metadata
    unable to create file listing for /workspace
    unable to create file listing
    unable to open file /workspace/.git/hooks/pre-commit
    open /workspace/.git/hooks/pre-commit: no such file or directory
  ERROR: failed to build: exit status 1
  ERROR: failed to build: executing lifecycle: failed with status code: 145
  ```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

  I used `pack` in the version `0.18.1+git-b5c1a96.build-2373`

* What buildpacks are you using? Please include versions.
    ```
    paketo-buildpacks/ca-certificates   2.2.0
    paketo-buildpacks/bellsoft-liberica 8.0.0
    paketo-buildpacks/gradle            5.2.0
    paketo-buildpacks/executable-jar    5.0.0
    paketo-buildpacks/apache-tomcat     5.3.0
    paketo-buildpacks/dist-zip          4.0.0
    paketo-buildpacks/spring-boot       4.2.0
    ```
* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
  ```
  paketobuildpacks/builder:base
  Digest: sha256:583b30158deddb27e5e8f78489e12fb5e77340f2ecd8e82ba300e28e58475955
  ```

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

  As already described above: [spring-music](https://github.com/scottfrederick/spring-music).

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
I have tried to reproduce this but cannot. Doing a `pack build` on Spring Music works for me on my local machine (MacOS).

It's possible that there are some file permissions issues happening in your environment. The part of the Gradle buildpack that's failing is attempting to walk the application directory to generate metadata for the layer. It seems that when it gets to `.git/hooks/pre-commit` it fails saying it can't find the file.

I would suggest:

1. Take a look at the file permissions and see if anything odd jumps out. For me it looks like this:

```
 ls -l .git/hooks/
total 80
-rwxr-xr-x  1 dmikusa  staff   452 Oct  2  2014 applypatch-msg.sample
-rwxr-xr-x  1 dmikusa  staff   896 Oct  2  2014 commit-msg.sample
-rwxr-xr-x  1 dmikusa  staff   189 Oct  2  2014 post-update.sample
-rwxr-xr-x  1 dmikusa  staff   398 Oct  2  2014 pre-applypatch.sample
-rwxr-xr-x  1 dmikusa  staff  1642 Oct  2  2014 pre-commit.sample
-rwxr-xr-x  1 dmikusa  staff  1352 Oct  2  2014 pre-push.sample
-rwxr-xr-x  1 dmikusa  staff  4951 Oct  2  2014 pre-rebase.sample
-rwxr-xr-x  1 dmikusa  staff  1239 Oct  2  2014 prepare-commit-msg.sample
-rwxr-xr-x  1 dmikusa  staff  3611 Oct  2  2014 update.sample
```

2. If you're still getting stuck, you can add a `project.toml` file and exclude the `.git` directory. I don't think you'd need that for any part of the build. See https://buildpacks.io/docs/app-developer-guide/using-project-descriptor/.

Lastly, to be thorough, what OS and Shell/terminal are you using? 

Thanks

**Comment by Haegi** [comment]
@dmikusa-pivotal thanks for the fast answer.
Unfortunately, I missed to note down that the hook is a symlink.
```bash
> ls -l .git/hooks/
total 16
-rwxr-xr-x  1 d070374  staff  51 May 18 14:31 post-commit
lrwxr-xr-x  1 d070374  staff  52 May 18 14:31 pre-commit -> <my-directories>/pre-commit
-rwxr-xr-x  1 d070374  staff  58 May 18 14:31 prepare-commit-msg
```
Excluding the `.git` directory with a `project.toml` file works for me but I'm still wondering why this buildpack wants to access my git hooks. Other buildpacks don't want to access it.

OS: `macOS Big Sur`
Shell/terminal: `zsh`

**Comment by dmikusa-pivotal** [comment]
It's not accessing it for any specific Gradle functionality, just for layer caching (i.e. to make the buildpack faster). 

It looks at the entire application that's pushed and creates a hash of it. The buildpack uses this hash, and some other metadata, to determine if it needs to run again next time you build the image. If the buildpack doesn't need to run again, it skips the entire layer using the cached one instead which is much faster.

It needs to look at your application files because if you change one of them, then it needs to rebuild instead of using the cached layer.

It should be safe to ignore the `.git` folder. I could perhaps see some optimizations in the buildpack around git as well. Possibly using the git commit hash to determine if there are app changes or even just ignoring that folder by default when we perform checks. I'll make a note to explore this possibility later.

Let me know if you have any more questions.

**Comment by dmikusa-pivotal** [comment]
FYI, https://github.com/paketo-buildpacks/libpak/issues/55

**Comment by Haegi** [comment]
Thanks for the detailed explanation!

**Comment by dmikusa-pivotal** [comment]
OK so https://github.com/paketo-buildpacks/libpak/pull/72 should fix the underlying issue here. The file listing in libpak had a bug where it could not handle symlinks to directories. Once we cut a release with #72 and update buildpacks to pick it up, this error should go away. I'm going to close out this issue.

I'm going to leave libpak#55 open though as I still think there's a potential for buildpack optimizations like always skipping the `.git` folder for file listings, which often has a lot of files and shouldn't matter for the purposes of building the application.
